### ISSUE TITLE
숙제

### ISSUE THREAD

**Issue by 11220** [developer-kerry/Gukwon-Kakaotalk-Chatbot#6]
어렵다..

**Comment by developer-kerry** [comment]
사실 지금 Git 사용법을 배우는 건  좀 많이 빠르긴 하지. 그런데 협업을 하려면, Git보다 체계적이고 정확한 도구가 없어서 어쩔 수 없다 ㅠㅠ...  그래도 언젠가는 지금부터 컨트리뷰트 남기는 게 도움이 될 거야. CLI 다루는 데 익숙하지 않으면 잠깐동안은 SourceTree같은거 써도 괜찮아. 암튼 고생했다,,
