### ISSUE TITLE
숙제

### ISSUE THREAD

**Issue by Sandvichmakemedead** [developer-kerry/Gukwon-Kakaotalk-Chatbot#7]
복잡...
그래도 할만할거 같은...

**Comment by developer-kerry** [comment]
ㅋㅋㅋ 많이 쓰다 보면 괜찮아질 거야. 서웅이랑 나랑 원종이랑 코딩하면서 계속 커밋-푸시 넣다보면 이틀이면 적응될 걸. 아무튼 수고한다~~
